#!/usr/bin/env python
import argparse
import pathlib

from speaktex import speaktex
from speaktex.speaktex import TexSpeaker


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('texfile', type=pathlib.Path)

    args = parser.parse_args()

    speaker = TexSpeaker()
    speaker.speaktex(args.texfile)


if __name__ == '__main__':
    main()
