#!/usr/bin/env python
import argparse
import pathlib

from speaktex import speaktex


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('texfile', type=pathlib.Path)

    args = parser.parse_args()

    speaktex.speaktex(args.texfile)


if __name__ == '__main__':
    main()
